In [ ]:
 import pandas as pd
 import numpy as np

In [ ]:
data = {
    "Energy Source ":["Solar","Wind","Hydropower","Geothermal","Biomas","nuclera" ],
    "Energy Consumption (MWh)":[1200,np.nan,2900,np.nan,2500,3200],
    "Cost(Million $)":[200,400,np.nan,150,250,np.nan]
}

In [ ]:
energy_df = pd.DataFrame(data)

In [ ]:
print("Original Energy Data with missing values\n ")
print(energy_df)

Original Energy Data with missing values

  Energy Source   Energy Consumption (kWh)  Cost(Million $)
0          Solar                    1200.0            200.0
1           Wind                       NaN            400.0
2     Hydropower                    2900.0              NaN
3     Geothermal                       NaN            150.0
4         Biomas                    2500.0            250.0
5        nuclera                    3200.0              NaN

In [ ]:
energy_df

  Energy Source   Energy Consumption (MWh)  Cost(Million $)
0          Solar                    1200.0            200.0
1           Wind                       NaN            400.0
2     Hydropower                    2900.0              NaN
3     Geothermal                       NaN            150.0
4         Biomas                    2500.0            250.0
5        nuclera                    3200.0              NaN

In [ ]:
energy_df.head(3)

  Energy Source   Energy Consumption (MWh)  Cost(Million $)
0          Solar                    1200.0            200.0
1           Wind                       NaN            400.0
2     Hydropower                    2900.0              NaN

In [ ]:
energy_df.tail(3)

  Energy Source   Energy Consumption (MWh)  Cost(Million $)
3     Geothermal                       NaN            150.0
4         Biomas                    2500.0            250.0
5        nuclera                    3200.0              NaN

In [ ]:
energy_df.shape

(6, 3)

In [ ]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Energy Source             6 non-null      object
 1   Energy Consumption (MWh)  4 non-null      float64
 2   Cost(Million $)           4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 276.0+ bytes

In [ ]:
energy_df.describe()

       Energy Consumption (MWh)  Cost(Million $)
count                  4.000000         4.000000
mean                2450.000000       250.000000
std                  881.286938       108.012345
min                 1200.000000       150.000000
25%                 2175.000000       187.500000
50%                 2700.000000       225.000000
75%                 2975.000000       287.500000
max                 3200.000000       400.000000

In [ ]:
energy_df.describe(include="all")

       Energy Source   Energy Consumption (MWh)  Cost(Million $)
count               6                  4.000000         4.000000
unique              6                       NaN              NaN
top             Solar                       NaN              NaN
freq                1                       NaN              NaN
mean              NaN               2450.000000       250.000000
std               NaN                881.286938       108.012345
min               NaN               1200.000000       150.000000
25%               NaN               2175.000000       187.500000
50%               NaN               2700.000000       225.000000
75%               NaN               2975.000000       287.500000
max               NaN               3200.000000       400.000000

In [ ]:
energy_df.describe() .T

,count,mean,std,min,25%,50%,75%,max
Energy Consumption (MWh),4.0,2450.0,881.286938,1200.0,2175.0,2700.0,2975.0,3200.0
Cost(Million $),4.0,250.0,108.012345,150.0,187.5,225.0,287.5,400.0

In [ ]:
energy_df.isnull().sum().sum()

np.int64(4)

In [ ]:
energy_df.shape

(6, 3)

In [ ]:
cleaned_df=energy_df.dropna()

In [ ]:
print("\n Data after removing Rows with missing values ")
print(cleaned_df)

 DAta after removing Rows with missing values
  Energy Source   Energy Consumption (MWh)  Cost(Million $)
0          Solar                    1200.0            200.0
4         Biomas                    2500.0            250.0

In [ ]:
energy_df.columns

Index(['Energy Source ', 'Energy Consumption (MWh)', 'Cost(Million $)'], dtype='object')

In [ ]:
energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(),inplace=True)
energy_df["Cost(Million $)"].fillna(energy_df["Cost(Million $)"].mean(),inplace=True) # what ever changes done i want that in original data set
print("\n Data After Impuing Missing Values with Mean:")
print(energy_df)

 Data After Impuing Missing Values with Mean:
  Energy Source   Energy Consumption (MWh)  Cost(Million $)
0          Solar                    1200.0            200.0
1           Wind                    2450.0            400.0
2     Hydropower                    2900.0            250.0
3     Geothermal                    2450.0            150.0
4         Biomas                    2500.0            250.0
5        nuclera                    3200.0            250.0

/tmp/ipykernel_277/2530518588.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df["Cost(Million $)"].fillna(energy_df["Cost(Million $)"].mean(),inplace=True)

In [ ]:
energy_df.columns

Index(['Energy Source ', 'Energy Consumption (MWh)', 'Cost(Million $)'], dtype='object')

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
energy_df[["Energy Consumption (MWh)","Cost(Million $)" ]] = scaler.fit_transform(
energy_df[["Energy Consumption (MWh)","Cost(Million $)"]]     )

print("\n Data After Normalization (Min-Max Scalling):")
print(energy_df)

 Data After Normalization (Min-Max Scalling):
  Energy Source   Energy Consumption (MWh)  Cost(Million $)
0          Solar                     0.000              0.2
1           Wind                     0.625              1.0
2     Hydropower                     0.850              0.4
3     Geothermal                     0.625              0.0
4         Biomas                     0.650              0.4
5        nuclera                     1.000              0.4

In [ ]:
energy_encoded_df = pd.get_dummies(energy_df,columns=["Energy Source "])

print("\n Data after one-hot encoding:")
print(energy_encoded_df)

 Data after one-hot encoding:
   Energy Consumption (MWh)  Cost(Million $)  Energy Source _Biomas  \
0                     0.000              0.2                  False
1                     0.625              1.0                  False
2                     0.850              0.4                  False
3                     0.625              0.0                  False
4                     0.650              0.4                   True
5                     1.000              0.4                  False

   Energy Source _Geothermal  Energy Source _Hydropower  Energy Source _Solar  \
0                      False                      False                  True
1                      False                      False                 False
2                      False                       True                 False
3                       True                      False                 False
4                      False                      False                 False
5                      False                      False                 False

   Energy Source _Wind  Energy Source _nuclera
0                False                   False
1                 True                   False
2                False                   False
3                False                   False
4                False                   False
5                False                    True

In [ ]:
energy_encoded_df["Consumption per $Million"]= energy_encoded_df["Energy Consumption (MWh)"] / energy_encoded_df["Cost(Million $)"]

print("\n Data with New Feature (Consumption per $Million):")
print(energy_encoded_df)

 Data with New Feature (Consumption per $Million):
   Energy Consumption (MWh)  Cost(Million $)  Energy Source _Biomas  \
0                     0.000              0.2                  False
1                     0.625              1.0                  False
2                     0.850              0.4                  False
3                     0.625              0.0                  False
4                     0.650              0.4                   True
5                     1.000              0.4                  False

   Energy Source _Geothermal  Energy Source _Hydropower  Energy Source _Solar  \
0                      False                      False                  True
1                      False                      False                 False
2                      False                       True                 False
3                       True                      False                 False
4                      False                      False                 False
5                      False                      False                 False

   Energy Source _Wind  Energy Source _nuclera  Consumption per $Million
0                False                   False                     0.000
1                 True                   False                     0.625
2                False                   False                     2.125
3                False                   False                       inf
4                False                   False                     1.625
5                False                    True                     2.500

In [ ]:
energy_encoded_df.columns

Index(['Energy Consumption (MWh)', 'Cost(Million $)', 'Energy Source _Biomas',
       'Energy Source _Geothermal', 'Energy Source _Hydropower',
       'Energy Source _Solar', 'Energy Source _Wind', 'Energy Source _nuclera',
       'Consumption per $Million'],
      dtype='object')